services:
  minimal_manager.module_list:
      class: MinimalOriginal\CoreBundle\Modules\ModuleList

  minimal_manager.module.core:
      class: MinimalOriginal\CoreBundle\MinimalModule
      tags: [minimal_manager.module]

  minimal_core.twig.text_extension:
    class: MinimalOriginal\CoreBundle\Twig\TextExtension
    tags:
        - { name: twig.extension }



  MinimalOriginal\CoreBundle\Form\AppType:
      arguments: ['@doctrine.orm.entity_manager']
      tags: [form.type]

  MinimalOriginal\CoreBundle\Doctrine\EventListener\RoutingSubscriber:
      arguments: ["@minimal_manager.module_list"]
      tags:
            - { name: doctrine.event_subscriber }

  MinimalOriginal\CoreBundle\HttpKernel\EventListener\Listener:
    tags: [kernel.event_subscriber]

  minimal_exposure_annotation_manager:
      class: MinimalOriginal\CoreBundle\Annotation\ExposureManager
      arguments: ["@annotation_reader"]

# Twig extensions
  minimal_core.twig.pagination_extension:
    class: MinimalOriginal\CoreBundle\Twig\PaginationExtension
    tags:
        - { name: twig.extension }

  minimal_core.twig.seo_extension:
    class: MinimalOriginal\CoreBundle\Twig\SeoExtension
    calls:
      - [setContainer, ["@service_container"]]
    tags:
        - { name: twig.extension }

# Routes Loaders
  minimal_annotation_class_loader:
      class: MinimalOriginal\CoreBundle\Routing\Loader\AnnotationClassLoader
      arguments: ["@annotation_reader", "@doctrine.orm.entity_manager"]
      tags: [routing.loader]

  MinimalOriginal\CoreBundle\Routing\Loader\AnnotationFileLoader:
      arguments: ["@file_locator", "@minimal_annotation_class_loader"]
      tags: [routing.loader]

  MinimalOriginal\CoreBundle\Routing\Loader\AnnotationDirectoryLoader:
      arguments: ["@file_locator", "@minimal_annotation_class_loader"]
      tags: [routing.loader]

# App parameters
  minimal_app_parameters:
    class: MinimalOriginal\CoreBundle\Service\AppParameters
    arguments: ["@doctrine.orm.entity_manager"]

# SEO
  minimal_seo:
    class: MinimalOriginal\CoreBundle\Service\Seo
